package com.example.ds.tree.traversal;


public enum Order {
    PRE_ORDER,
    ITERATIVE_PRE_ORDER,
    IN_ORDER,
    ITERATIVE_IN_ORDER,
    POST_ORDER,
    ITERATIVE_POST_ORDER,
    LEVEL_ORDER,
    LEVEL_ORDER_LINE_BY_LINE,
    LEVEL_ORDER_LINE_BY_LINE_2_QUEUES,
    REVERSE_LEVEL_ORDER,
    ZIG_ZAG_ORDER,
    VERTICAL_ORDER,
    LEFT_VIEW,
    RIGHT_VIEW,
    TOP_VIEW,
    BOTTOM_VIEW,
    BOUNDARY;
}
